version: '3.3'
services:
    api:
        build:
            context: ../api
            dockerfile: ../docker/api.dev.Dockerfile
        container_name: DevOps_API
        restart: unless-stopped
        networks:
            - network
        volumes:
            - ../api:/usr/src/api
        expose:
            - 7000
        ports:
            - 7000:7000
        env_file: ../api/.env
        environment:
            WAIT_HOSTS: db:27018
            WAIT_HOSTS_TIMEOUT: 120
    db:
        image: mongo:latest
        container_name: DevOps_DB
        volumes:
            - ./data:/data/db
        ports:
            - '27018:27018'
        networks:
            - network
    client:
        stdin_open: true
        build:
            context: ../client
            dockerfile: ../docker/client.dev.Dockerfile
        container_name: DevOps_CLIENT
        restart: unless-stopped
        networks:
            - network
        volumes:
            - ../client:/usr/src/client
        ports:
            - 3005:3000
        # env_file: ../api.env
networks:
    network:
        driver: bridge