version: '3.3'
services:
    api:
        build:
            context: ../api
            dockerfile: ../docker/api.prod.Dockerfile
        container_name: DevOps_API
        restart: unless-stopped
        networks:
            - network
        volumes:
            - ../api:/usr/src/api
        expose:
            - 7000
        ports:
            - 7000:7000
        env_file: ../api/.env
        environment:
            WAIT_HOSTS: db:27018,redis:6379
            WAIT_HOSTS_TIMEOUT: 120
    db:
        image: mongo:latest
        container_name: DevOps_DB
        volumes:
            - ./data:/data/db
        ports:
            - '27018:27018'
        networks:
            - network
    client:
        build:
            context: ../client
            dockerfile: ../docker/client.prod.Dockerfile
        container_name: DevOps_CLIENT
        restart: unless-stopped
        networks:
            - network
        ports:
            - 80:80
        volumes:
            - ./devops.template:/etc/nginx/conf.d/devops.template

networks:
    network:
        driver: bridge